// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE1Iuo2BdiXxM3sQbuywx7-YWvOZWI27Q',
    appId: '1:181915445130:web:32e3fae01b321182ec4a73',
    messagingSenderId: '181915445130',
    projectId: 'algobuddy-bf96c',
    authDomain: 'algobuddy-bf96c.firebaseapp.com',
    storageBucket: 'algobuddy-bf96c.firebasestorage.app',
    measurementId: 'G-Q809VBZRTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRt_EWpY-kz6zsLew02hm0ZBT_6OQ09IM',
    appId: '1:181915445130:android:07d5c6b60df9417cec4a73',
    messagingSenderId: '181915445130',
    projectId: 'algobuddy-bf96c',
    storageBucket: 'algobuddy-bf96c.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY8xjbckjSzFbsN4kooF3DXSN3xBoXDOo',
    appId: '1:181915445130:ios:38013c9ac9a42a0cec4a73',
    messagingSenderId: '181915445130',
    projectId: 'algobuddy-bf96c',
    storageBucket: 'algobuddy-bf96c.firebasestorage.app',
    iosBundleId: 'com.example.buddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE1Iuo2BdiXxM3sQbuywx7-YWvOZWI27Q',
    appId: '1:181915445130:web:31b654d74a16fa89ec4a73',
    messagingSenderId: '181915445130',
    projectId: 'algobuddy-bf96c',
    authDomain: 'algobuddy-bf96c.firebaseapp.com',
    storageBucket: 'algobuddy-bf96c.firebasestorage.app',
    measurementId: 'G-N2BZ5WRG9N',
  );
}
