// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFLF3d7gQH3bz_W1lgUkBAluWFdU0KYys',
    appId: '1:297251602321:web:3debf580ca7e52bb056430',
    messagingSenderId: '297251602321',
    projectId: 'algobudget-3e4d2',
    authDomain: 'algobudget-3e4d2.firebaseapp.com',
    storageBucket: 'algobudget-3e4d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXL969sMWAKyhB7rqOMv2NJl7W5eHLboA',
    appId: '1:297251602321:android:9e44c866d88bdd95056430',
    messagingSenderId: '297251602321',
    projectId: 'algobudget-3e4d2',
    storageBucket: 'algobudget-3e4d2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByNRbcm_K8x1UcgzUKunTxjn887vxjFkk',
    appId: '1:297251602321:ios:cfcfacda963e5ee0056430',
    messagingSenderId: '297251602321',
    projectId: 'algobudget-3e4d2',
    storageBucket: 'algobudget-3e4d2.firebasestorage.app',
    iosClientId: '297251602321-725mbcbii32v162u42gto0646n8tkkbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFLF3d7gQH3bz_W1lgUkBAluWFdU0KYys',
    appId: '1:297251602321:web:dcd2e759a0b3f030056430',
    messagingSenderId: '297251602321',
    projectId: 'algobudget-3e4d2',
    authDomain: 'algobudget-3e4d2.firebaseapp.com',
    storageBucket: 'algobudget-3e4d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByNRbcm_K8x1UcgzUKunTxjn887vxjFkk',
    appId: '1:297251602321:ios:cfcfacda963e5ee0056430',
    messagingSenderId: '297251602321',
    projectId: 'algobudget-3e4d2',
    storageBucket: 'algobudget-3e4d2.firebasestorage.app',
    iosClientId: '297251602321-725mbcbii32v162u42gto0646n8tkkbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddy',
  );

}